/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupLoginRouteImport } from './routes/signup-login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SignupLoginRoute = SignupLoginRouteImport.update({
  id: '/signup-login',
  path: '/signup-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/goals': typeof GoalsRoute
  '/logs': typeof LogsRoute
  '/signup-login': typeof SignupLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/goals': typeof GoalsRoute
  '/logs': typeof LogsRoute
  '/signup-login': typeof SignupLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/goals': typeof GoalsRoute
  '/logs': typeof LogsRoute
  '/signup-login': typeof SignupLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/goals' | '/logs' | '/signup-login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/goals' | '/logs' | '/signup-login'
  id: '__root__' | '/' | '/about' | '/goals' | '/logs' | '/signup-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GoalsRoute: typeof GoalsRoute
  LogsRoute: typeof LogsRoute
  SignupLoginRoute: typeof SignupLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup-login': {
      id: '/signup-login'
      path: '/signup-login'
      fullPath: '/signup-login'
      preLoaderRoute: typeof SignupLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GoalsRoute: GoalsRoute,
  LogsRoute: LogsRoute,
  SignupLoginRoute: SignupLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
