/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupLoginRouteImport } from './routes/signup-login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsFoodSearchRouteImport } from './routes/logs/food-search'
import { Route as AuthPasskeyEnrollmentRouteImport } from './routes/auth/passkey-enrollment'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRecoveryRouteImport } from './routes/auth/login-recovery'

const SignupLoginRoute = SignupLoginRouteImport.update({
  id: '/signup-login',
  path: '/signup-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsFoodSearchRoute = LogsFoodSearchRouteImport.update({
  id: '/food-search',
  path: '/food-search',
  getParentRoute: () => LogsRoute,
} as any)
const AuthPasskeyEnrollmentRoute = AuthPasskeyEnrollmentRouteImport.update({
  id: '/auth/passkey-enrollment',
  path: '/auth/passkey-enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRecoveryRoute = AuthLoginRecoveryRouteImport.update({
  id: '/auth/login-recovery',
  path: '/auth/login-recovery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/goals': typeof GoalsRoute
  '/logs': typeof LogsRouteWithChildren
  '/signup-login': typeof SignupLoginRoute
  '/auth/login-recovery': typeof AuthLoginRecoveryRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/passkey-enrollment': typeof AuthPasskeyEnrollmentRoute
  '/logs/food-search': typeof LogsFoodSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/goals': typeof GoalsRoute
  '/logs': typeof LogsRouteWithChildren
  '/signup-login': typeof SignupLoginRoute
  '/auth/login-recovery': typeof AuthLoginRecoveryRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/passkey-enrollment': typeof AuthPasskeyEnrollmentRoute
  '/logs/food-search': typeof LogsFoodSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/goals': typeof GoalsRoute
  '/logs': typeof LogsRouteWithChildren
  '/signup-login': typeof SignupLoginRoute
  '/auth/login-recovery': typeof AuthLoginRecoveryRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/passkey-enrollment': typeof AuthPasskeyEnrollmentRoute
  '/logs/food-search': typeof LogsFoodSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/goals'
    | '/logs'
    | '/signup-login'
    | '/auth/login-recovery'
    | '/auth/otp'
    | '/auth/passkey-enrollment'
    | '/logs/food-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/goals'
    | '/logs'
    | '/signup-login'
    | '/auth/login-recovery'
    | '/auth/otp'
    | '/auth/passkey-enrollment'
    | '/logs/food-search'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/goals'
    | '/logs'
    | '/signup-login'
    | '/auth/login-recovery'
    | '/auth/otp'
    | '/auth/passkey-enrollment'
    | '/logs/food-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GoalsRoute: typeof GoalsRoute
  LogsRoute: typeof LogsRouteWithChildren
  SignupLoginRoute: typeof SignupLoginRoute
  AuthLoginRecoveryRoute: typeof AuthLoginRecoveryRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthPasskeyEnrollmentRoute: typeof AuthPasskeyEnrollmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup-login': {
      id: '/signup-login'
      path: '/signup-login'
      fullPath: '/signup-login'
      preLoaderRoute: typeof SignupLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/food-search': {
      id: '/logs/food-search'
      path: '/food-search'
      fullPath: '/logs/food-search'
      preLoaderRoute: typeof LogsFoodSearchRouteImport
      parentRoute: typeof LogsRoute
    }
    '/auth/passkey-enrollment': {
      id: '/auth/passkey-enrollment'
      path: '/auth/passkey-enrollment'
      fullPath: '/auth/passkey-enrollment'
      preLoaderRoute: typeof AuthPasskeyEnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login-recovery': {
      id: '/auth/login-recovery'
      path: '/auth/login-recovery'
      fullPath: '/auth/login-recovery'
      preLoaderRoute: typeof AuthLoginRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LogsRouteChildren {
  LogsFoodSearchRoute: typeof LogsFoodSearchRoute
}

const LogsRouteChildren: LogsRouteChildren = {
  LogsFoodSearchRoute: LogsFoodSearchRoute,
}

const LogsRouteWithChildren = LogsRoute._addFileChildren(LogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GoalsRoute: GoalsRoute,
  LogsRoute: LogsRouteWithChildren,
  SignupLoginRoute: SignupLoginRoute,
  AuthLoginRecoveryRoute: AuthLoginRecoveryRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthPasskeyEnrollmentRoute: AuthPasskeyEnrollmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
